spring:
  application:
    name: spring-cloud-ribbon-service

server:
  port: 9092

  
  
# Discovery Server Access (Client Service that invokes call on Person Service)
#  1. Define URL of registration server (defaultZone)
#  2. Reduce lease-renewal time so processes register more quickly
eureka:
  instance:
     leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
      